# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-06 19:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=160)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('postid', models.CharField(max_length=10000)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default=b'images/default.jpg', upload_to=b'images')),
                ('first_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('age', models.CharField(blank=True, max_length=3)),
                ('bio', models.CharField(blank=True, max_length=430)),
                ('creation_time', models.DateTimeField()),
                ('update_time', models.DateTimeField(blank=True)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entry_creators', to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=160)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('comments', models.ManyToManyField(blank=True, null=True, related_name='comments', to='socialnetwork.Comments')),
                ('entry', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='socialnetwork.Entry')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
